services:
  openbao:
    image: quay.io/openbao/openbao:latest
    container_name: openbao
    ports:
      - "8200:8200"
    environment:
      BAO_DEV_ROOT_TOKEN_ID: dev-token
      BAO_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server -dev
